language: scala
dist: trusty
sudo: true
services:
  - docker

scala:
  - 2.11.12
  - 2.12.7
  # - 2.13.0-M4

jdk:
  - openjdk8

matrix:
  include:
    - scala: 2.12.7
      jdk: openjdk9
    - scala: 2.12.7
      jdk: openjdk10
    - scala: 2.12.7
      jdk: openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.coursier
    - $HOME/.cache/install-jdk

install:
  - pip install --user codecov

script:
  - |
    if [[ "$TRAVIS_JDK_VERSION" = "openjdk8" && "$TRAVIS_SCALA_VERSION" = 2.12.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION clean coverage test "examples/run" coverageReport coverageOff && codecov
    else
      sbt ++$TRAVIS_SCALA_VERSION clean test
    fi
  - |
    if [[ "$TRAVIS_JDK_VERSION" = "openjdk8" && "$TRAVIS_BRANCH" = "master" && $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
      gpg_key_path=$HOME/.gnupg
      mkdir -p $gpg_key_path
      echo $GPG_KEY | base64 --decode > $gpg_key_path/secring.gpg
      export PGP_SECRET_RING=$gpg_key_path/secring.gpg
      sbt ++$TRAVIS_SCALA_VERSION publishSigned
    fi

after_script:
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
