name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        scala:
          [2.12.16, 2.13.8, 3.2.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.11
      - run: sbt ++${{ matrix.scala }} coverage test coverageReport
      - run: sbt ++${{ matrix.scala }} examples/run
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          verbose: true
