name: Tagging

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          skip-github-pull-request: true
